[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/upstream-history"
  to = "https://www.sciencedirect.com/science/article/pii/S0142727X25002620"
  status = 301
  force = true

[dev]
  command = "vite"
  port = 3000
  publish = "dist"