[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"
  ignore = "false"
  force = "true"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  NETLIFY_BUILD_SKIP = "false"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/upstream-history"
  to = "https://www.sciencedirect.com/science/article/pii/S0142727X25002620"
  status = 301
  force = true

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
